### ISSUE TITLE
Setting custom GPG key results in a misleading error-level log entries

### ISSUE THREAD

**Issue by arturopala** [sbt/sbt-pgp#174]
Custom GPG key set with `usePgpKeyHex` results in a misleading `[error]` level log entries for each signed file, e.g.:

```
[error] gpg: using "XXXXXXXXXXXXXXXXXXXX" as default secret key for signing
```

tested with `"com.jsuereth"      % "sbt-pgp"      % "2.0.1"` and
```
gpg --version
gpg (GnuPG/MacGPG2) 2.2.17
libgcrypt 1.8.5
```

**Comment by samzilverberg** [comment]
i second that.
was publishing today and thought signing was failing because of the error level log lines.
but it actually had no problem signing and was successful.

the log level should just be info or debug.

I spent 10-15 mins searching throuh the code (release v2.0.1) for the culprit but didn't find anything :(

**Comment by eed3si9n** [comment]
I'm guessing this is due to sys process wrapper reporting stderr output as `[error]`. For example

https://github.com/sbt/sbt-pgp/blob/b0baebc62260450b1efad2943a897a8b21653c90/sbt-pgp/src/main/scala/com/jsuereth/sbtpgp/PgpSigner.scala#L46-L49

We need to change the implementation of `s.log` to `ProcessLogger` conversion. See https://github.com/sbt/util/blob/v1.3.3/internal/util-logging/src/main/scala/sbt/util/Logger.scala.

Would either of you interested in sending a PR for this?
