### ISSUE TITLE
Hooking into publish

### ISSUE THREAD

**Issue by jodersky** [sbt/sbt-pgp#85]
This is more of a question rather than an issue.

Why does sbt-pgp not change the default functionality of `publish` and `publishLocal`, instead it defines its own tasks `publishSigned`? The documentation says

> sbt-pgp no longer wires in to the default publish and publish-local tasks of SBT

but gives no explanation as to why the functionality was removed.

One advantage of modifying `publish` would be seamless integration with other plugins such as `sbt-release`, without the need of explicitly depending in them. What are the disadvantages?

**Comment by jodersky** [comment]
Anyone got any info on this?

**Comment by jsuereth** [comment]
Sorry for the late replay @jodersky,  the reason we don't do that is because it is actually flaky.   sbt-pgp had no way of SAFELY hooking `publish` and ensuring it signed all artifacts.

There is an alternative way to hook ivy for signing things, but it's not exposed in sbt (and is a bit ugly to do so), so this mechanism is currently the easiest/best.
